const questionPool = [
    {
        question: "Which language runs in a web browser?",
        option1: "Java",
        option2: "C",
        option3: "Python",
        option4: "JavaScript",
        correctAnswer: "option4",
    },
    {
        question: "What does CSS stand for?",
        option1: "Central Style Sheets",
        option2: "Cascading Style Sheets",
        option3: "Cascading Simple Sheets",
        option4: "Cars SUVs Sailboats",
        correctAnswer: "option2",
    },
    {
        question: "What does HTML stand for?",
        option1: "Hypertext Markup Language",
        option2: "Hypertext Markdown Language",
        option3: "Hyperloop Machine Language",
        option4: "Helicopters Terminals Motorboats Lamborghinis",
        correctAnswer: "option1",
    },
    {
        question: "What year was JavaScript launched?",
        option1: "1996",
        option2: "1995",
        option3: "1994",
        option4: "none of the above",
        correctAnswer: "option2",
    },
    {
        question: "What is the purpose of a 'for' loop in programming?",
        option1: "To declare variables",
        option2: "To perform a specific task repeatedly",
        option3: "To define functions",
        option4: "To handle exceptions",
        correctAnswer: "option2",
    },
    {
        question: "Which data type is not primitive in JavaScript?",
        option1: "String",
        option2: "Number",
        option3: "Boolean",
        option4: "Object",
        correctAnswer: "option4",
    },
    {
        question: "What is the significance of version control systems like Git?",
        option1: "Managing project dependencies",
        option2: "Tracking changes in code over time",
        option3: "Optimizing code execution",
        option4: "Creating user interfaces",
        correctAnswer: "option2",
    },
    {
        question: "In programming, what is the purpose of the 'else' statement?",
        option1: "To handle errors",
        option2: "To execute code when a condition is true",
        option3: "To execute code when a condition is false",
        option4: "To define variables",
        correctAnswer: "option3",
    },
    {
        question: "What is the role of the 'npm' command in Node.js development?",
        option1: "Executing JavaScript files",
        option2: "Managing project dependencies",
        option3: "Creating HTML documents",
        option4: "Optimizing database queries",
        correctAnswer: "option2",
    },
    {
        question: "Which symbol is used for single-line comments in many programming languages?",
        option1: "//",
        option2: "/*",
        option3: "--",
        option4: "#",
        correctAnswer: "option1",
    },
    {
        question: "What is the purpose of the 'this' keyword in JavaScript?",
        option1: "Declaring variables",
        option2: "Referring to the current object",
        option3: "Defining functions",
        option4: "Handling exceptions",
        correctAnswer: "option2",
    },
    {
        question: "Which programming paradigm does JavaScript primarily follow?",
        option1: "Imperative",
        option2: "Declarative",
        option3: "Functional",
        option4: "Procedural",
        correctAnswer: "option3",
    },
    {
        question: "What is the role of the 'SQL' language in database management?",
        option1: "Styling web pages",
        option2: "Querying and managing databases",
        option3: "Creating animations",
        option4: "Handling user inputs",
        correctAnswer: "option2",
    },
    {
        question: "Which symbol is used to access properties of an object in JavaScript?",
        option1: ".",
        option2: ":",
        option3: "->",
        option4: "::",
        correctAnswer: "option1",
    },
    {
        question: "What is the result of 5 + 8?",
        option1: "10",
        option2: "12",
        option3: "13",
        option4: "15",
        correctAnswer: "option3",
    },
    {
        question: "In mathematics, what does 'PI' represent?",
        option1: "3.1415926535",
        option2: "2.7182818284",
        option3: "1.6180339887",
        option4: "4.6692016091",
        correctAnswer: "option1",
    },
    {
        question: "What is the square root of 144?",
        option1: "9",
        option2: "12",
        option3: "15",
        option4: "144",
        correctAnswer: "option2",
    },
    {
        question: "If x = 3 and y = 5, what is the value of 2x + y?",
        option1: "11",
        option2: "13",
        option3: "16",
        option4: "21",
        correctAnswer: "option1",
    },
    {
        question: "What is the area of a rectangle with length 7 units and width 4 units?",
        option1: "18",
        option2: "24",
        option3: "28",
        option4: "32",
        correctAnswer: "option2",
    },
    {
        question: "Solve for 'x': 2x - 8 = 12.",
        option1: "8",
        option2: "10",
        option3: "12",
        option4: "14",
        correctAnswer: "option4",
    },
    {
        question: "What is the value of 3! (3 factorial)?",
        option1: "3",
        option2: "6",
        option3: "9",
        option4: "12",
        correctAnswer: "option2",
    },
    {
        question: "If a = 4 and b = 7, what is the value of a^2 + b^2?",
        option1: "41",
        option2: "49",
        option3: "53",
        option4: "65",
        correctAnswer: "option2",
    },
    {
        question: "What is the result of 9 divided by 3?",
        option1: "2",
        option2: "3",
        option3: "4",
        option4: "5",
        correctAnswer: "option2",
    },
    {
        question: "If a triangle has angles of 30°, 60°, and 90°, what type of triangle is it?",
        option1: "Equilateral",
        option2: "Isosceles",
        option3: "Scalene",
        option4: "Right-angled",
        correctAnswer: "option4",
    },
    {
        question: "In what year did World War II end?",
        option1: "1943",
        option2: "1945",
        option3: "1950",
        option4: "1960",
        correctAnswer: "option2",
    },
    {
        question: "Who was the first President of the United States?",
        option1: "Thomas Jefferson",
        option2: "George Washington",
        option3: "Abraham Lincoln",
        option4: "John Adams",
        correctAnswer: "option2",
    },
    {
        question: "What ancient civilization built the pyramids of Giza?",
        option1: "Roman Empire",
        option2: "Greek Civilization",
        option3: "Ancient Egyptians",
        option4: "Mesopotamians",
        correctAnswer: "option3",
    },
    {
        question: "In which year did Christopher Columbus reach the Americas?",
        option1: "1492",
        option2: "1510",
        option3: "1607",
        option4: "1620",
        correctAnswer: "option1",
    },
    {
        question: "Who was the famous nurse during the Crimean War and is considered the founder of modern nursing?",
        option1: "Florence Nightingale",
        option2: "Clara Barton",
        option3: "Mary Seacole",
        option4: "Dorothea Dix",
        correctAnswer: "option1",
    },
    {
        question: "What event marked the beginning of the Great Depression in the 1930s?",
        option1: "Stock Market Crash of 1929",
        option2: "World War I",
        option3: "Prohibition",
        option4: "Assassination of Archduke Franz Ferdinand",
        correctAnswer: "option1",
    },
    {
        question: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
        option1: "Nikita Khrushchev",
        option2: "Joseph Stalin",
        option3: "Leon Trotsky",
        option4: "Vladimir Lenin",
        correctAnswer: "option1",
    },
    {
        question: "Which ancient civilization was known for the development of democracy in the city-state of Athens?",
        option1: "Roman Empire",
        option2: "Persian Empire",
        option3: "Greek Civilization",
        option4: "Egyptian Civilization",
        correctAnswer: "option3",
    },
    {
        question: "In what year did the Berlin Wall fall, leading to the reunification of East and West Germany?",
        option1: "1985",
        option2: "1989",
        option3: "1991",
        option4: "1995",
        correctAnswer: "option2",
    },
    {
        question: "Who was the first woman to win a Nobel Prize, and in what field?",
        option1: "Marie Curie - Physics",
        option2: "Rosalind Franklin - Chemistry",
        option3: "Jane Goodall - Peace",
        option4: "Mother Teresa - Literature",
        correctAnswer: "option1",
    },
    {
        question: "What is the purpose of the 'let' keyword in JavaScript?",
        option1: "Declaring constants",
        option2: "Declaring variables with block scope",
        option3: "Defining functions",
        option4: "Handling asynchronous operations",
        correctAnswer: "option2",
    },
    {
        question: "What is the role of the 'JSON' object in JavaScript?",
        option1: "Managing DOM elements",
        option2: "Handling HTTP requests",
        option3: "Serializing and deserializing data",
        option4: "Creating animations",
        correctAnswer: "option3",
    },
    {
        question: "In JavaScript, what does the '===' operator compare?",
        option1: "Values and types",
        option2: "Values only",
        option3: "Types only",
        option4: "None of the above",
        correctAnswer: "option1",
    },
    {
        question: "What is an IIFE in JavaScript?",
        option1: "Inherited Internal Function Expression",
        option2: "Immediately Invoked Function Expression",
        option3: "Inline Iterative Function Execution",
        option4: "Internal Inline Function Encapsulation",
        correctAnswer: "option2",
    },
    {
        question: "What is the purpose of the 'map' function in JavaScript?",
        option1: "Iterating over an array and transforming its elements",
        option2: "Sorting an array alphabetically",
        option3: "Filtering elements in an array",
        option4: "Combining elements of two arrays",
        correctAnswer: "option1",
    },
    {
        question: "What is a 'closure' in JavaScript?",
        option1: "A type of loop",
        option2: "A type of variable",
        option3: "A function with access to its own scope and the outer function's scope",
        option4: "A data type",
        correctAnswer: "option3",
    },
    {
        question: "What is the purpose of the 'async' and 'await' keywords in JavaScript?",
        option1: "Defining asynchronous functions",
        option2: "Handling exceptions",
        option3: "Synchronous function declaration",
        option4: "Object-oriented programming",
        correctAnswer: "option1",
    },
    {
        question: "What is the difference between 'null' and 'undefined' in JavaScript?",
        option1: "'null' represents an intentionally absent value, while 'undefined' is an unintentionally absent value.",
        option2: "'null' and 'undefined' are the same and can be used interchangeably.",
        option3: "'undefined' represents an intentionally absent value, while 'null' is an unintentionally absent value.",
        option4: "There is no difference; they are synonyms.",
        correctAnswer: "option1",
    },
    {
        question: "What is the purpose of the 'bind' method in JavaScript?",
        option1: "To create a new array with the results of a provided function",
        option2: "To merge two or more arrays",
        option3: "To explicitly set the value of 'this' for a given function",
        option4: "To filter elements in an array",
        correctAnswer: "option3",
    },
    {
        question: "What is a 'Promise' in JavaScript?",
        option1: "A guarantee that a specific event will occur",
        option2: "An object representing the eventual completion or failure of an asynchronous operation",
        option3: "A type of variable",
        option4: "A built-in function for creating objects",
        correctAnswer: "option2",
    },
    {
        question: "What is the SI unit of force?",
        option1: "Newton",
        option2: "Watt",
        option3: "Joule",
        option4: "Pascal",
        correctAnswer: "option1",
    },
    {
        question: "According to Newton's second law of motion, what is the relationship between force, mass, and acceleration?",
        option1: "Force = Mass × Acceleration",
        option2: "Force = Mass / Acceleration",
        option3: "Force = Acceleration / Mass",
        option4: "Force = Acceleration + Mass",
        correctAnswer: "option1",
    },
    {
        question: "What is the speed of light in a vacuum?",
        option1: "300,000 km/s",
        option2: "500,000 km/s",
        option3: "700,000 km/s",
        option4: "900,000 km/s",
        correctAnswer: "option1",
    },
    {
        question: "What is the law of conservation of energy?",
        option1: "Energy can be created but not destroyed",
        option2: "Energy cannot be created or destroyed, only transferred or converted",
        option3: "Energy is always decreasing in a closed system",
        option4: "Energy is constant only in mechanical systems",
        correctAnswer: "option2",
    },
    {
        question: "What is the formula for calculating gravitational potential energy?",
        option1: "PE = mgh",
        option2: "PE = 1/2 mv²",
        option3: "PE = Fd",
        option4: "PE = E/t",
        correctAnswer: "option1",
    },
    {
        question: "What is the primary function of a concave lens?",
        option1: "To converge light rays",
        option2: "To diverge light rays",
        option3: "To block light",
        option4: "To absorb light",
        correctAnswer: "option2",
    },
];

export { questionPool };
